#server:
#  port:
#    9093
#
#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/MiniProject
#    password: root
#  jpa:
#    hibernate.ddl-auto: create
#
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      dialect: org.hibernate.dialect.MYSQL8Dialect